### ISSUE TITLE
What for `math.randomseed`

### ISSUE THREAD

**Issue by iSentrie** [JeesusKrisostoomus/Kyk-RedeemCodes#2]
Hey, so we got `math.randomseed` here, what is it for? While testing I noticed that it only breaks generator, try spamming generate code, it will output many same codes, without that `math.randomseed` it works as intended. You might want to take a look at it. ;)
```
function RandomCodeGenerator()
    math.randomseed(os.time())
	RandomCode = math.random(Config.minNumber, Config.maxNumber)
	return RandomCode
end
```
Example what it does for me:
![image](https://user-images.githubusercontent.com/29688478/95028836-03091300-06ac-11eb-85c7-6a857d1026ae.png)

**Comment by JeesusKrisostoomus** [comment]
You are right. It breaks everything.
Before it wasnt breaking somehow idk. Gonna remove it cus it seems to be useless now.
Ty for finding this.
