### ISSUE TITLE
Redeeming wrong code = console error

### ISSUE THREAD

**Issue by iSentrie** [JeesusKrisostoomus/Kyk-RedeemCodes#3]
While redeeming `/redeem <any random text>` it gives error to console. Not sure, but it should be for everyone. Couldn't fix this, weird, but it contradicts its own logic. I have no idea why.

The error line is
`if (args[1] == data[1].code) then`

While it should just print "Invalid code" it, throws that line error. Weird, you got this too?

EDIT: it gives that error from both ingame & console.

**Comment by JeesusKrisostoomus** [comment]
Yes. I am already trying to find out how i should fix this. I have a few methods in mind but havent tested them yet.

**Comment by JeesusKrisostoomus** [comment]
Found some kind of a fix for it. Probably aint the best but it works.
