### ISSUE TITLE
hello kyk-redeemcodes

### ISSUE THREAD

**Issue by tricell17** [JeesusKrisostoomus/Kyk-RedeemCodes#7]
i have suggestion add generates code for money and item.

**Comment by JeesusKrisostoomus** [comment]
Hi. Thanks for the suggestion. I will try implementing item rewards though i don't know when im gonna release the update. And under money do you mean cash or money that goes to your bank (If bank then that is already implemented)?

**Comment by tricell17** [comment]
cash. but we can make option for cash or bank i think

**Comment by JeesusKrisostoomus** [comment]
So i have gotten the system implemented. I am gonna do a few checks, fix a bug and then i will release it. Database.sql file will be changed aswell

**Comment by tricell17** [comment]
thanks you for replying.

**Comment by JeesusKrisostoomus** [comment]
Released the update. I didn't have the time to bug test but i will try to do some testing now.

**Comment by tricell17** [comment]
i already tested on my server thanks for update.

**Comment by tricell17** [comment]
now i going to make surprise box and give random weapon by grade, common, uncommon and rare but i still stuck on math.random and math.seed

**Comment by JeesusKrisostoomus** [comment]
If you need help then i might be able to help u in some time. Just hmu in discord: Jeesus Krisostoomus#7737

**Comment by tricell17** [comment]
alright then msg u by later
