### ISSUE TITLE
es_extended.RedeemCodes doesn't exist

### ISSUE THREAD

**Issue by xLamday** [JeesusKrisostoomus/Kyk-RedeemCodes#8]
> [  script:mysql-async] [MariaDB:10.4.20-MariaDB] [ERROR] [RedeemCodes] An error happens for query "SELECT * FROM `RedeemCodes` WHERE `code` = ? : ["FUW8TpdOqI"]": ER_NO_SUCH_TABLE: Table 'es_extended.RedeemCodes' doesn't exist

This is the error that appears when i try to create a normal code. 

I was looking into the client and server.lua and seems okay, maybe you should take a look.

Let me know asap, Thank You

**Comment by JeesusKrisostoomus** [comment]
Seems as if you havent added the database.sql to your database. If you have the table in your database try renaming it to RedeemCodes. Maybe it helps. If it does(or doesnt) work then lmk

**Comment by xLamday** [comment]
> Seems as if you havent added the database.sql to your database. If you have the table in your database try renaming it to RedeemCodes. Maybe it helps. If it does(or doesnt) work then lmk

I've already renamed it, i don't know what to do atm

**Comment by JeesusKrisostoomus** [comment]
> > Seems as if you havent added the database.sql to your database. If you have the table in your database try renaming it to RedeemCodes. Maybe it helps. If it does(or doesnt) work then lmk
> 
> I've already renamed it, i don't know what to do atm

I will have to get back to you when i get back to my compter so until then i dont really know what i could recommend you. Is there anywhere i could contact you besides github?

**Comment by xLamday** [comment]
> > > Seems as if you havent added the database.sql to your database. If you have the table in your database try renaming it to RedeemCodes. Maybe it helps. If it does(or doesnt) work then lmk
> > 
> > 
> > I've already renamed it, i don't know what to do atm
> 
> I will have to get back to you when i get back to my compter so until then i dont really know what i could recommend you. Is there anywhere i could contact you besides github?

You can contact me on Discord as well: хЛамдай#0446

**Comment by JeesusKrisostoomus** [comment]
> > > > Seems as if you havent added the database.sql to your database. If you have the table in your database try renaming it to RedeemCodes. Maybe it helps. If it does(or doesnt) work then lmk
> > > 
> > > 
> > > I've already renamed it, i don't know what to do atm
> > 
> > 
> > I will have to get back to you when i get back to my compter so until then i dont really know what i could recommend you. Is there anywhere i could contact you besides github?
> 
> You can contact me on Discord as well: хЛамдай#446

Hey. The discord you gave either doesn't exist (also you didnt include the last number) or i wasnt able to add you (trialing last num)
